package com.newsportal.domain.general;

public enum SubSection {
	NEWS_PRESS, NEWS_DAY_SUMMARY, NEWS_WARSZAWA, NEWS_LODZ, NEWS_SZCZECIN, NEWS_KIELCE, NEWS_OLSZTYN, NEWS_SLASK, NEWS_KRAKOW, NEWS_OPOLE, NEWS_TROJMIASTO, NEWS_KUJAWSKO_POMORSKIE, NEWS_POZNAN, NEWS_WROCLAW, NEWS_RZESZOW, NEWS_ZIELONA_GORA, NEWS_LUBLIN,
	SPORT_FOOTBALL_EKSTRAKLASA, SPORT_FOOTBALL_NIEMIECKA, SPORT_FOOTBALL_WLOSKA, SPORT_FOOTBALL_LIGA_MISTRZOW, SPORT_FOOTBALL_HISZPANSKA, SPORT_FOOTBALL_1LIGA, SPORT_FOOTBALL_LIGA_EUROPY, SPORT_FOOTBALL_PUCHAR_POLSKI, SPORT_FOOTBALL_ANGIELSKA, SPORT_FOOTBALL_FRANCUSKA, SPORT_FOOTBALL_EURO2012,
	BUSINESS_CURRENCIES, BUSINESS_PRESS, BUSINESS_COMMENTS, BUSINESS_ANALYSIS, BUSINESS_QUOTATIONS,
	TECH_GAMES, TECH_COMPUTERS, TECH_MOBILE, TECH_INTERNET, TECH_RTVAGD, TECH_MILITARY, TECH_NEWS, TECH_BUSINESS,
	MOTO_NEWS, MOTO_RELEASES, MOTO_TESTS, MOTO_MOTORCYCLES,
	KNOWLEDGE_SCIENCE, KNOWLEDGE_CULTURE, KNOWLEDGE_STUDENT, KNOWLEDGE_TRIPS,
	ENTERTAINMENT_MOVIES, ENTERTAINMENT_MUSIC,
	STYLE_WOMAN, STYLE_MAN,
	UNASSIGNED
}